### ISSUE TITLE
Estilo do tema

### ISSUE THREAD

**Issue by valeriosouza** [WordPressBeloHorizonte/horizon-theme#1]
Precisamos definir o estilo

Blog
Portifolio
Magazine
Institucional

**Comment by brenoalvs** [comment]
Entre esses quatro? Ou sugestões?

**Comment by valeriosouza** [comment]
Sugestões também. Lembrando que o Portifolio tem grandes chances de ser escolhido rsrs

**Comment by lacmaia** [comment]
Portfólio atrai mais...

**Comment by brenoalvs** [comment]
Ia sugerir pra loja virtual que também atrai bastante.

**Comment by valeriosouza** [comment]
Verdade, mas dá muito trabalho. Muita tela, muita integração

**Comment by brenoalvs** [comment]
Agora que vi que é pra lançar no WordCamp, aí realmente não dá xD

**Comment by ProfPandaRJ** [comment]
Na verdade se for usar o woo-commerce como plug-in pra loja virtual é fácil. Tenho feito diversas lojas usando o woocommerce e o odin, fica mais por questão de configurações css.

**Comment by matheusgimenez** [comment]
Voto pelo portfolio

**Comment by theandersonn** [comment]
Eu voto no Institucional.

Vai ajudar um galerão a criar temas de maneira correta onde vão ver que não é um bicho de sete cabeças e como o desenvolvimento será acelerado com o uso do WP.

**Comment by kyrvim** [comment]
Voto pelo portfolio

**Comment by rodrigo-brito** [comment]
Como tinha dito antes... o porrifólio é mais direcionado para a galera que cria e gerencia conteúdo e também é bem atrativo para os desenvolvedores. Voto Portifólio

**Comment by rodrigo-brito** [comment]
Acho que a iniciativa do porrifólio já teve uma boa adesão. Podemos fechar e partir para o Layout?

**Comment by brenoalvs** [comment]
Acho que poderia rolar um levantamento de requisitos antes do layout, só pra saber o que vai ter ou não no layout. Formato de posts, imagens destacadas, sliders, suporte pra customização, essas coisas.

**Comment by theandersonn** [comment]
Portfólio ganhou disparado sem dúvidas, mas ainda acho que Institucional tem mais apelo comercial; tipo o desenvolvedor poderá ampliar a ideia, customizar com necessidades especificas e trabalhar em cima deste tema.

Além do mais dentro do institucional pode ter um blog e uma seção de portfólio, então é mais abrangente.

**Comment by valeriosouza** [comment]
Continua no #3
