### ISSUE TITLE
Retirar require que está gerando erro na ativação do tema

### ISSUE THREAD

**Issue by leobaiano** [WordPressBeloHorizonte/horizon-theme#18]
Na linha 25 do arquivo functions.php temos uma chamada para um arquivo que não existe:

``` php
require_once get_template_directory() . '/core/classes/widgets/class-widget-like-box.php';
```

É preciso retirar porque está chamada está gerando erro na ativação do tema.

**Comment by claudiosanches** [comment]
606f736442222684e2136f57e21c024690a17abd
