### ISSUE TITLE
Odin?

### ISSUE THREAD

**Issue by brenoalvs** [WordPressBeloHorizonte/horizon-theme#2]
O tema vai pro repositório oficial, certo?
Dá pra usar o Odin ou tem algum problema?

**Comment by valeriosouza** [comment]
Sim, vamos usar o Odin e vai sim pro repositório.

**Comment by ProfPandaRJ** [comment]
Beleza, já existe um psd de como será a aparência do tema?

**Comment by brenoalvs** [comment]
@ProfPandaRJ na #1 estão discutindo primeiro qual será o propósito do tema.

**Comment by brenoalvs** [comment]
Acho que primeiro precisa definir a #1 pra depois alguém layoutar.

**Comment by rodrigo-brito** [comment]
Odin na veia =D
A integração com o bootstrap e algumas classes vão facilitar bastante o trabalho.
