### ISSUE TITLE
Criar diretório para anexos

### ISSUE THREAD

**Issue by brenoalvs** [WordPressBeloHorizonte/horizon-theme#20]
Criar um diretório para os "anexos", segue a estrutura de pastas:
- dev
  - psds (psds do projeto)
  - jpgs (para visualização rápida)
  - data (xml com dummy data)

Algo mais?

**Comment by nicholasio** [comment]
Talvez uma documentação? Semelhante aos temas premium

**Comment by brenoalvs** [comment]
É uma boa tbm!
--edit--
@nicholasio  acabei de lembrar que a documentação pode ser feita aqui mesmo pela Wiki!
