### ISSUE TITLE
Erro no Gruntfile.js

### ISSUE THREAD

**Issue by nicholasio** [WordPressBeloHorizonte/horizon-theme#22]
Ao tentar rodar o grunt, é exibido um erro de sintaxe, nesta parte:

``` javascript
        // Uglify to concat and minify
        uglify: {
            dist: {
                files: {
                    '<%= dirs.js %>/main.min.js': [
                        '<%= dirs.js %>/main.js'
                    ]
                }
            }}
            }
        },
```

Além disso está acusando a falta do arquivo .jshint. A correção do erro de sintaxe é só remover as chaves que tem a mais.

Alguém pode rever este arquivo e configs do grunt? Não manjo muito de grunt, trabalho mais com o gulp.js.

**Comment by rodrigo-brito** [comment]
No arquivo atual tem duas chaves sobrando na linha 42 e 43, remove ae que compila numa boa.

![grunt](https://cloud.githubusercontent.com/assets/7620947/6931501/51c254fe-d7e4-11e4-892e-1443c48dfa36.jpg)

**Comment by nicholasio** [comment]
fixed #24

**Comment by claudiosanches** [comment]
Calma ai galera, só joguei a base, agora vamos ir arrumando e colocando as coisas certas.
