### ISSUE TITLE
Bug ao instalar o grunt

### ISSUE THREAD

**Issue by valeriosouza** [WordPressBeloHorizonte/horizon-theme#28]
Ao instalar o grunt na raiz do tema, recebo o erro.
![captura de tela 2015-04-02 as 08 38 45](https://cloud.githubusercontent.com/assets/1946271/6965541/bbd6cfa6-d928-11e4-92cb-ec5c6320fb37.png)

**Comment by rodrigo-brito** [comment]
Ontem o sass começou a dar uns erros para comprimir os arquivos de css, fui dar uma olhara e eram alguns parâmetros que não estavam sendo reconhecidos `--output-style` do sass. O packege.json está instalando o `"grunt-contrib-sass": "~0.9.2"`. Pelo que vi na documentação dele, o comando para definir o estilo de saída era o `style: 'compressed'`, e não o : `outputStyle: 'compressed'` como está no Gruntfile.js. os parâmentros de saída que estão lá são de outra versão, o "grunt-sass", pelo que vi aqui no Google.

Troquei aqui agora a versão do package.json e parou de dar problema, será que é isso?
Atual: `"grunt-sass": "~0.18.1",`

**Comment by mksanti** [comment]
@valeriosouza  muito extranho esse erro, ta parecendo bug no node. Tenta re-instalar todo. Node, grunt e sass e nao esquece de colocar em modo global. Pode ser que resolva.

**Comment by claudiosanches** [comment]
@rodrigo-brito você que quebrou ele https://github.com/WordPressBeloHorizonte/horizon-theme/commit/2b56644eaabee1124758baa23d684762d180c191#diff-35b4a816e0441e6a375cd925af50752c ;)

**Comment by rodrigo-brito** [comment]
husahushua vou voltar a config, nem tinha visto isso.

**Comment by valeriosouza** [comment]
Vamos focar no meu bug? Uma issue pra cada erro!

**Comment by rodrigo-brito** [comment]
@valeriosouza da uma checada nessa issue https://github.com/gruntjs/grunt-contrib-imagemin/issues/291

O problema do cara é praticamente o mesmo, e no caso dele era a versão do Node que é incompatível `node v0.13.0-pre`, mesma versão que a sua.

**Comment by claudiosanches** [comment]
Acabei de atualizar o `package.json` e tudo esta funcionando ok.
Versão estável do node hoje é `v0.12.2`.
Seu ambiente esta zuado @valeriosouza
