### ISSUE TITLE
Necessidades do tema portfólio 

### ISSUE THREAD

**Issue by valeriosouza** [WordPressBeloHorizonte/horizon-theme#3]
Descreva as necessidades, áreas e tudo que precisa ter no tema

**Comment by brenoalvs** [comment]
Acho que o básico é: 
- Blog
- Páginas
- Menu customizável
- Área de widgets
- Algumas customizações de Aparência

Aí algumas sugestões, além do básico:
- Área de projetos
- Galeria de imagens para cada projeto (usando a galeria padrão ou customizada)
- Alguns metadados "padrões" para os projetos (Cliente, URL, ano...)
- Widget com últimos projetos

**Comment by rodrigo-brito** [comment]
- Blog
- Páginas
- Home Full Width
  - Carrossel com divulgação de serviços
  - 3 Blocos com Textos Clichês que toda empresa coloca
  - Grid com os projetos do porrifólio com filtro por tipo e carregamento ajax (Ex: Mansory, isotope, etc)
  - Carrossel com a logo dos clientes
  - Form básico de contato
  - Mapa abaixo opicional caso o cliente queira setar um endereço para localização.

Os projetos e os clientes podem ser CPT com alguns campos específicos e a área separada no Painel facilitaria a gestão.

**Comment by brenoalvs** [comment]
Acho que os clientes poderiam ser uma taxonomia dos projetos, facilitaria o cruzamento dos dados. Visto que um cliente pode ter vários projetos, pode rolar um archive dos clientes.

**Comment by rodrigo-brito** [comment]
Pensei nos clientes como CPT apenas para ter um Thumbnail com o logotipo, link para site ou página na web e também aquela área lateral para inserção que facilitaria o gerenciamento. Acho que a listagem de projetos não necessária mente precisa ser associado a um cliente, pois não vai ficar nada armazenado sobre ele, ou vai?

**Comment by brenoalvs** [comment]
Mas thumb e link podem ser metadados de uma taxonomy, e assim ganhamos o archive e a relação entre os dois. E isso não obriga, a ter uma relação, só dá a opção de ter.

Quanto ao menu, a taxonomy fica como submenu dos projetos (padrão)

**Comment by rodrigo-brito** [comment]
Show de bola então @brenoalvs , eu não sabia sobre essa possibilidade de edição de metadados para as taxonomias personalizadas.

**Comment by theandersonn** [comment]
É importante que seja Responsivo.

**Comment by rodrigo-brito** [comment]
@theandersonn o Odin utiliza o bootstrap, é sussa.

**Comment by brenoalvs** [comment]
Nada mais? Tinha que chamar mais gente pra contribuir, depois reclamam xD

**Comment by valeriosouza** [comment]
Precisamos de um designer, o que prontificou a fazer sumiu. Né Daniel?

**Comment by brenoalvs** [comment]
Eu faço uns rabiscos de vez em quando!
Se nenhum designer se aprensentar, tento fazer algo...

**Comment by DanielGCarvalho** [comment]
Rapaz, sumi nada, a vida é que anda corrida mesmo. Vou montar algo este FDS pra já aprovarmos o layout.

**Comment by brenoalvs** [comment]
Show, mas vamos em frente com esses requisitos mesmo?

**Comment by DanielGCarvalho** [comment]
Acredito que sim

**Comment by rodrigo-brito** [comment]
Se sobrar tempo vamos tirando mais ideias da cartola =D

**Comment by DanielGCarvalho** [comment]
É isso aí pessoal, segue a primeira amostra para o tema horizon. Segue também a logo criada para o projeto, acho que o conceito ficou bem legal. Aguardo um retorno. Cortesia da ArteDC![home_horizon](https://cloud.githubusercontent.com/assets/6988830/6891014/ff8749fa-d68b-11e4-9e34-e044da39df23.jpg)

**Comment by rodrigo-brito** [comment]
Ta show de bola, acho que o menu ficaria massa se fosse assim o hover/active
O que acham?
![menu](https://cloud.githubusercontent.com/assets/7620947/6894087/d28748d4-d6a8-11e4-8954-4ab27123b9b5.jpg)

**Comment by valeriosouza** [comment]
Ficou foda. Curti o single page. Curti o segundo estilo de haver.

**Comment by nicholasio** [comment]
Curti o layout e sobre o menu ia sugerir o mesmo que o @rodrigo73 sugeriu!

**Comment by valeriosouza** [comment]
Vou fechar essa Issue e abrir uma só pro layout
