### ISSUE TITLE
Remoção de módulos do Bootstrap

### ISSUE THREAD

**Issue by rodrigo-brito** [WordPressBeloHorizonte/horizon-theme#30]
Acho que tem muita coisa no bootstrap que pode ser removido, não conheço muito bem as dependências de arquivos do bootstrap, mas podíamos enumerar o que vai ser utilizar e removemos o resto.

Utilizado até o momento
- Grid
- Navbar
- Dropdown

**Comment by rodrigo-brito** [comment]
Sugestão
![core bootstrap](https://cloud.githubusercontent.com/assets/7620947/6970007/186c87f4-d949-11e4-8aa6-dd3b84c43b1c.jpg)

**Comment by claudiosanches** [comment]
Acho que ainda tem muita coisa xD
Pra mim ficaria só o normalize e fariamos tudo do zero mesmo :p

**Comment by nicholasio** [comment]
@claudiosmweb  Já estamos usando o Bootstrap, só se refizesse tudo...

**Comment by claudiosanches** [comment]
@nicholasio bootstrap vai limitar muito aqui, sendo que daria para fazer algo bem melhor.
Sem contar o menu que Bootstrap por padrão aceita apenas dois níveis e no WordPress podemos ir além.

**Comment by nicholasio** [comment]
@claudiosmweb tem workaround já pra essa questão dos níveis, mas tinha ficado certo que os menus só teriam um nível. De qualquer forma usamos Bootstrap porquê tinha ficado definido no começo das discussões.

**Comment by claudiosanches** [comment]
Vocês que vão fazer os estilos, mas como eu falei, é se limitar e se prender demais, ainda mais para as pessoas que estão no projeto.

**Comment by rodrigo-brito** [comment]
Em relação aos níveis do menu acho que não tem problema, o pessoal falou que rola uns problemas de acessibilidade. O problema do bootstrap é que ele sobrepõe muito css e acaba que fica muita coisa atoa no arquivo de estilo. Mas facilita bastante o trabalho. Comprimida, essa config chega a uns 50KB acho que está razoável.

**Comment by mksanti** [comment]
Eu dei a ideia de a gente criar um mini framework... até porque nao sao muitos componentes que o layout tem, antes mesmo de agente começar a usar o Bootstrap. Porém optaram por usar ele, na minha opinião além da limitação, tem muito recurso que nao vamos usar, o html fica cheio de divs a mais e se perde mais tempo tentando limpar o FW.

**Comment by brenoalvs** [comment]
Eu acho uma boa fazer esse front do zero usando Stylus! xD
Tem muito tempo que não mexo no bootstrap, tô enferrujado e acho que tem bastante gente assim tbm.
Dá pra fazer uma folha de grid, uma folha de variables e começar!

**Comment by nicholasio** [comment]
Eu acho que cada um vai sugerir usar a tecnologia que sabe ou gosta. Por mim também poderia fazer do zero, mas já tinha ficado definido boostrap então começamos com bootstrap.

**Comment by brenoalvs** [comment]
Estava só brincando quanto ao Stylus, acho que convém muito mais usar SASS em um projeto open-source. Só que, quanto ao bootstrap, não tenho certeza se vai ser tão essencial ao projeto.

**Comment by theandersonn** [comment]
Essa questão de indefinição atrapalha o andamento mesmo.

No meu caso ainda não sou hábil com SASS; sei trabalhar com Bootstrap, seu grid e algumas funcionalidades, ainda não explorei todas.

Atualmente estou fazendo testes com esse Grid Responsivo:
Lemonade

https://github.com/dope/lemonade/blob/master/README.md

**Comment by rodrigo-brito** [comment]
Por mim tanto faz, eu estou aqui só para participar mesmo.
Eu sugeri a divisão do bootstrap porque o pessoal falou que ia ser o odin, mas se quiser passar para outra coisa da na mesma. Só precisa ter um grid, nunca usei o stylus, então não posso nem opinar.

**Comment by rodrigo-brito** [comment]
Se a questão for só o grid é tranquilo.... tem muito grid leve tipo o http://960.gs/
Mas isso é bobeira... qualquer um atende bem.

**Comment by valeriosouza** [comment]
Bom, eu não sou especialista em front-end, dei a ideia do bootstrap pode ser popular e fácil uso. Se a ideia é popularizar, a ideia é deixar ele fácil uso. Não adianta fazer bonito, fazer certo e não ser popular.

**Comment by brenoalvs** [comment]
@valeriosouza  Acho que o problema é que temos poucos elementos de interface compatíveis com o Bootstrap, então vamos usá-lo muito pouco, ou vai acabar sendo necessário alterar algo a um ponto que seria melhor ter feito do zero. Só o normalize e um grid já resolveria o que precisamos, de resto podemos continuar com SASS que acho que é o pré-processador mais popular

Mas se quiserem seguir com o Bootstrap, vamos em frente!

**Comment by claudiosanches** [comment]
Grid em Sass tem que ser com o http://susy.oddbird.net/

**Comment by miguelsmuller** [comment]
Comecei a usar o usar o susy a uns 2 ou 3 projetos atrás quando larguei o bootstrap e nao me arrependo.

**Comment by mksanti** [comment]
Enquanto vocês decidem se vao usar BS ou não, fiz uma versao sem BS.
O front esta 70% pronto, todo responsivo, fiz ele utilizando sass como pre-processador com alguns mixins propios que me ajudam no desenvolvimento e jeet.gs como grid. Esta muito facil de dar manutenção, porque além de utilizar variaveis tentei componetizar o layout ao maximo. 

Quero esclarecer que nao tenho nada contra BS ou qualquer outro FW, porém os motivos que me levaram a fazer esta versão foram os seguintes:

1 - O layout nao tem nem 0,5% do dos componentes do BS, atualmente estamos usando somente 3
- Grid | Podemos usar qualquer um que se adapte ao projeto (susy, 960, semantic) eu optei por jeet.
- Navbar | Pode ser feito em apensa 5 min e totalmente personalizado e sem a nescesidade de colocar muitas div no html
- Dropdown | Sou daqueles que colocam a perfomance e usabilidade do site como prioridade, o BS para fazer os dropdown utiliza js, neste caso eu criei os submenus somente com css.

2 - Percebi que podiamos fazer algumas melhoras no front atual como por exemplo, as sections que estao com imagens ( antes e depois da section serviços ), atualmente quando você diminui o browser a imagem esta cortando e em determinada largura some. De nada adianta dar display:none se vai ser carregada do mesmo jeito, então eu reogarnizer de um jeito que agente possa aproveitar a imagem sem perder a usabilidade. 

3 - Rapidez... No caso de usar BS, temos que ficar limpando modulos que nao vamos a usar e ter cuidado para nao sobre escrever classes, pra mim estas tarefas demanda tempo, que pode ser aproveitado para criar qualquer outra coisa. Com apenas alguns functions, mixins e linhas de codigos, consegui desenvolver esta versão em 3 horas e meia.

Esta aqui minha contribuição https://github.com/mikejavier/horizon-theme-alt caso queiram dar uma olhada e fiquem a vontade para pegar os estilos e adaptarem para a versão atual. Amanhã acredito terminar o  restante do front.

**Comment by nicholasio** [comment]
Sobre o ponto 2: A imagem grande, a do banner, acho que não faz muito sentido deixar em smartphones, não sei se você testou, mas fica muito pequeno e o texto fica por debaixo do menu, a minha sugestão tinha sido tirar a imagem e deixar só o texto "Eu sou Horizon" para smartphones.

Também vi outras detalhes que não estão de acordo com o PSD, mas se decidirmos por usar essa sua versão eu listo/crio as issues depois.

Bom... agora temos duas versões: Com BS e com Jeet.js. @mikejavier espera a galera decidir antes de finalizar.

@valeriosouza o que acha?

**Comment by rodrigo-brito** [comment]
O CSS minificado está em 106kB, acho que continua na mesma situação do BS.
Eu não conheço muito bem essas outras frameworks de css, então é melhor deixar para os mestres ai decidirem!
Ficou bom o layout @mikejavier.

**Comment by mksanti** [comment]
@nicholasio Concordo com você naquela primeira imagem principal, o texto n da para ver, eu somente fiz colar a imagem. As outras coisas que nao estão de acordo ao psd, foram sugestões mas ai entra a opiniao de todo mundo e vamos ajustando da melhor forma. E independentemente da galera escolher ou não vou terminar o front, gostei do layout e me deu vontade de fazer :D 

@rodrigo-brito O css nao esta minificado e as imagens também não. Como nao ainda estou terminando... não me preocupei em fazer isso.  E como citei lá em cima enquanto o bootstrap já carregou jquery + js e ainda css, aqui somente esta com html e css.

**Comment by nicholasio** [comment]
@mikejavier ah entendi, mas eu acredito que aquele texto é independente da imagem. por isso deva ser colocado por cima da imagem. Inclusive eu usei alinhamento vertical lá pra centralizar o texto e por isso também não era possível (pelo menos não consegui) usar o alinhamento vertical com uma altura variável (ditada pela imagem), por isso optei por deixar a altura fixa e ir cortando as laterais até que a imagem desaparece..

Sobre as mudanças em relação ao PSD tem que ver se o @DanielGCarvalho aprova!

**Comment by leobaiano** [comment]
Galera, acho que é melhor a gente abrir pra votação sobre como será feito o front do tema, com fw, sem fw, se for com fw qual será... Digo isso porque daqui a pouco alguém vai e faz sua versão com susy, outro vai e faz com foundation e terminamos perdendo tempo com versões que podem nem ser utilizadas. Na minha opinião é mais válido parar um pouco e definir como será.

**Comment by nicholasio** [comment]
Concordo com @leobaiano... é o que já tinha sugerido no #46.

**Comment by valeriosouza** [comment]
Dando meu voto como falei no #46, e aqui. Eu acho bootstrap mais popular e povão, portanto mais vendável e de fácil acesso, sem precisar ter nada o cara consegue trabalhar. Enfim, não sou especialista, o que me preocupa é o tema ser de fácil uso pra qualquer ser humano alterar e trabalhar.

**Comment by leobaiano** [comment]
Pessoal, criei uma enquete para resolver essa questão, segue o link: http://goo.gl/forms/3FPE8QMvQm

**Comment by claudiosanches** [comment]
> Eu acho bootstrap mais popular e povão

Galera só vai baixar este tema e usar como ele foi feito, ninguém vai falar:

> Nossa é feito com Bootstrap, vai ser fácil para personalizar!

Mas também não acho que deve rolar votação, agora o projeto já correu bastante com Bootstrap, então vamos nessa com ele.
Assim não precisamos voltar no que já esta pronto.

**Comment by mksanti** [comment]
@claudiosmweb nao prescisa voltar para o que já esta pronto.. eu fiz esta versao sem BS. https://github.com/mikejavier/horizon-theme-alt. Foi ai que começou a votação se fazia com BS ou não.

**Comment by rodrigo-brito** [comment]
Bolas pra frente com o BS então?

**Comment by leobaiano** [comment]
Temos 11 votos e 7 colaboradores, acho que já da pra fechar a votação.

**Comment by brenoalvs** [comment]
@valeriosouza  concordo com o Cláudio e acho que no nosso caso não temos uma interface complexa com vários elementos de UI. Só precisamos de alguns elementos mesmo e também por isso não dá pra vender muito esse peixe de Bootstrap.

Não acho que andamos tanto assim com o projeto, dava pra fazê-lo do zero. Mas, particularmente, acho que se vamos usar o bootstrap, devemos fazê-lo de forma inteligente. Usar só o que for realmente necessário.

Prender alguns elementos do nosso layout ao bootstrap (só porque tem lá) é ruim porque gera muito código desnecessário. (como é o caso da navbar).

Acho que deveríamos focar no que é realmente útil para o projeto e não tentar fazer um projeto em cima do bootstrap.

**Comment by nicholasio** [comment]
@brenoalvs em #46 estamos usando só o que é necessário, muitos componentes ficarão do BS ficarão de fora.

Mas como o assunto já foi votado e decidido acredito que podemos fechar essa issue e seguir em frente.
