### ISSUE TITLE
Rotina de Pull Request

### ISSUE THREAD

**Issue by rodrigo-brito** [WordPressBeloHorizonte/horizon-theme#40]
Vamos supor que eu já esteja um editando um branch e alguém atualiza o repositório original, tem problema de enviar o PR com o repositório em versões diferentes? Tem como atualizar o fork antes de enviar o PR? Não achei nada para atualizar pelo GitHub, pelo git tem como puxar um repositório diferente do fork clonado? Eu fico apagando e clonando toda hora, mas suspeito que tenha outra maneira.
Se alguém ai puder me dar uma força, comecei esse ano com o GitHub e estou tomando porrada legal pra esses comandos.

Vlw!

**Comment by leobaiano** [comment]
@rodrigo-brito para atualizar o seu fork você vai fazer o seguinte:

`
git remote add upstream git://github.com/WordPressBeloHorizonte/horizon-theme.git
`

Depois:
`
git pull upstream master
`

Isso vai baixar os arquivos atualizados do repositório para o seu repositório local. Então você faz um push `git push -u origin master` para atualizar seu fork no github e pode trabalhar.

Agora vamos supor que você está trabalhando em uma branch e antes de terminar ela ocorreram atualizações no master, não tem problema é justamente para isso que as branch existem, se houverem conflitos eles terão que ser resolvidos na hora que for mesclar com o master.

**Comment by rodrigo-brito** [comment]
Funcionou aqui @leobaiano 
Eu estava apagando a pasta toda hora aqui para ficar atualizando.

Vlw pela ajuda, abraços!
