### ISSUE TITLE
Área de Serviços - Serviços da Horizon

### ISSUE THREAD

**Issue by nicholasio** [WordPressBeloHorizonte/horizon-theme#50]
Desenvolvimento da área de serviços na home.

**Comment by leobaiano** [comment]
Estava pensando sobre os ícones dessa área aqui, vamos criar uma galeria com vários ícones e permitir que o desenvolvedor ou usuário definam qual ícone de cada serviço? Vamos deixar aberto para que as pessoas possam fazer upload do ícone? Estou pensando nisso porque interfere um pouco no front end, tipo, se for permitir que as pessoas façam upload não seria legal colocar a imagem via css, com background por exemplo, para não ter que usar css inline na hora de montar o back end.

Não é nada demais, mas quem for fazer o front dessa parte é bom pensar em uma forma que facilite para quem vai utilizar o tema.

**Comment by nicholasio** [comment]
Verdade @leobaiano, tava pensando nisso também. Acredito que agente possa criar a galeria com os ícones predefinidos e também dar a opção do usuário enviar um ícone customizado, tendo em vista que nosso público é mais abrangente e um tema desse deva ser o mais customizável possível.

**Comment by nicholasio** [comment]
Uma situação semelhante acontece no separador que mostra as habilidades #51

**Comment by rodrigo-brito** [comment]
Acho que é uma boa criar um CPT para cadastrar serviços, la ele seta a descrição, título e o ícone, para listagem. E fica livre para a pessoal não se prender ao número de itens de serviços.

**Comment by leobaiano** [comment]
Tinha pensado em CPT mesmo. Desta forma ai é bom exibir o icone como imagem no HTML mesmo e não como background via CSS.

**Comment by valeriosouza** [comment]
Será um CPT, mas isso é parte do backend

**Comment by leobaiano** [comment]
Sim @valeriosouza tô ligado que é back, mas é que se a galera exibir o icone via CSS fica ruim depois no back pra chamar a imagem dinamicamente, termina tendo que colocar CSS inline e isso é uma merda.

**Comment by brenoalvs** [comment]
A gente pode fazer um seletor de icon font!
Acho que nas icon fonts já tem tantas opções que perde até o sentido de colocar um ícone customizado. Sem contar, que vejo isso como uma boa UX, só assim o usuário não pode colocar um ícone que fuja da identidade visual do site.

**Comment by leobaiano** [comment]
@brenoalvs icon fonts é legal, até porque da para atrelar a cor do ícone a uma das cores definidas nas configurações do tema, porém tira do desenvolvedor/ usuário que for usar o tema a liberdade de subir um ícone que ele deseje.

**Comment by nicholasio** [comment]
@brenoalvs acho que é uma boa também.

@leobaiano mas acredito que possamos usar o icon font e dar a opção para o usuário enviar a imagem dele.

**Comment by rodrigo-brito** [comment]
Acho que podia deixar livre a questão dos ícones, dá mais liberdade para o usuário.

**Comment by brenoalvs** [comment]
Concordo com o @nicholasio podemos usar as duas opções, resolvendo assim o problema.
Mas tem icon fonts hoje tão extensas, que o usuário só vai querer subir um ícone próprio em casos extremos.

**Comment by nicholasio** [comment]
@brenoalvs pode ajudar nessa questão dos icon fonts? Nunca gerei um icon fonts.

**Comment by brenoalvs** [comment]
Tava pensando em pegarmos um pronto com mais opções, o @DanielGCarvalho poderia ver um compatível com a id do site. Mas também podemos vetorizar os ícones dos .psds (se já não estão) e fazer um. Só que isso diminui as opções...

**Comment by rodrigo-brito** [comment]
o Font Awesome (http://fortawesome.github.io/Font-Awesome/) tem mais de 500 ícones, vai facilitar bastante pois o seletor de ícones dele é por classe de css, o desafio vai ser gerenciar isso no painel administrativo, nem faço ideia se é possível.

**Comment by brenoalvs** [comment]
O font awesome tem bastante opções mas acho foge um pouco da id do site (eles são meio redondos, os atuais são mais elegantes).

Não é nenhuma novidade não @rodrigo-brito já tem alguns temas premium que fazem isso, e acredito que vá ser menos complicado do que com as imagens. Eu pego até essa issue pra fazer :D

**Comment by brenoalvs** [comment]
Não é nenhuma novidade não @rodrigo-brito já tem alguns temas premium que faz isso, e acredito que vá ser menos complicado do que com as imagens. Eu pego até essa issue pra fazer :D

**Comment by rodrigo-brito** [comment]
Show!! O esquema vai ser encontrar um kit bacana de ícones então ne.

**Comment by brenoalvs** [comment]
Algumas opções então
- [Font Awesome](http://fortawesome.github.io/Font-Awesome/)
- [Dashicons](https://developer.wordpress.org/resource/dashicons/#editor-ul) - Padrão do WordPress
- [Icomoon](https://icomoon.io/) - Não sei se é compatível com GPL

Também temos:
- [Esse repositório foda](http://weloveiconfonts.com/) de icon fonts open-source
- E claro, tem a do [Bootstrap](http://getbootstrap.com/components/#glyphicons) que já estamos usando!

Quem for fazer o front dessa issue, é só manter o mesmo esquema  dos glyphicons do Bootstrap que já agiliza.

**Comment by rodrigo-brito** [comment]
Achei um showcase do GitHub, tem bastante opção

https://github.com/showcases/icon-fonts

**Comment by brenoalvs** [comment]
Show! O mais importante é ser compatível com a GPL

**Comment by leobaiano** [comment]
Pronto, então faz usando o dashicons mesmo e no back end a gente monta a opção de escolher um dos ícones disponíveis ou subir um arquivo.

Falo do dashicons porque é o padrão do WP e acho que atende, mas pode ser a awesome.

Todo mundo concorda?

**Comment by nicholasio** [comment]
Acho que poderíamos decidir entre dashicons e glyphicons já que um vem com WordPress e o outro vem com o Bootstrap (apesar de estar desabilitado).

Talvez o @DanielGCarvalho deva opinar sobre isso.

**Comment by mksanti** [comment]
Se vocês nao conhecem tem o Flat icon, possue mts packs de todos os tipos e para todas as ocasioes, vocês também selecionar somente os que querem e acredito que pode ajudar vcs.

http://www.flaticon.com/

**Comment by brenoalvs** [comment]
@leobaiano acho que o problema do dashicons é que tem poucas opções relacionadas a portfolio.
Também acho que @DanielGCarvalho deveria dar a cartada final, afinal ele que fez o design, rs.

E tanto faz se for importar o glyphicons (tbm é o meu preferido, por enquanto) ou qualquer outro, a maioria funciona no mesmo esquema de classes css, não tem mistério...

**Comment by nicholasio** [comment]
+1 glyphicons.

EDIT: -1 glyphicons não é GPL

**Comment by valeriosouza** [comment]
Glyphicons não é GPL pelo que sei. Ela tem parte free e paga. Vamos usar dashicons e awesome. Opção da pessoa escolher.

**Comment by valeriosouza** [comment]
Definido isso já, Bora começar dar gás, Daniel tá meio agarrado esses dias.
