### ISSUE TITLE
Área de Portfólio - Porftifólio da Horizon

### ISSUE THREAD

**Issue by nicholasio** [WordPressBeloHorizonte/horizon-theme#52]
Desenvolvimento do portifólio na home.

**Comment by rodrigo-brito** [comment]
Pegando essa agora pela manhã!

**Comment by nicholasio** [comment]
Feito em #63

**Comment by leobaiano** [comment]
Os cases estão sem links, vai ser assim mesmo?

**Comment by brenoalvs** [comment]
@leobaiano, vou colocar o Masonry e adiciono os links sem problemas.

**Comment by nicholasio** [comment]
Isso aqui precisa estar aberto ainda? O Masonry foi deixado de lado correto? Os links adicionam na issue do back.

**Comment by brenoalvs** [comment]
@nicholasio tinha deixado a issue do masonry aberta, pra fazê-la como enhacement mais tarde, mas deixa fechada por enquanto.

**Comment by nicholasio** [comment]
Fechando. Criei nova issue específica para implementar o mansory: #94
