### ISSUE TITLE
Rodapé

### ISSUE THREAD

**Issue by nicholasio** [WordPressBeloHorizonte/horizon-theme#55]
Desenvolvimento do Rodapé

**Comment by rodrigo-brito** [comment]
Vou pegar essa issue agora a tarde.

**Comment by nicholasio** [comment]
Deixando aberto porquê falta colocar os ícones no rodapé.

**Comment by rodrigo-brito** [comment]
Fica pendente a questão do icon fonts, mas isso é tranquilo de ajeitar depois.
