### ISSUE TITLE
Front-end

### ISSUE THREAD

**Issue by valeriosouza** [WordPressBeloHorizonte/horizon-theme#6]
Como vamos dividir a criação do front? Cada um pega uma parte? Vamos usar Sass?

**Comment by deblynprado** [comment]
Cada um pegar uma parte acho que pode dar vários conflitos xD

acho que o ideal seria centralizar e um faz o esqueleto... a partir daí abrem-se as issues das coisas que precisam ser feitas e nego vai pegando e fazendo.

**Comment by valeriosouza** [comment]
Alguém quer fazer isso? Alguém bom de front-end e que consiga entregar no prazo?

**Comment by nicholasio** [comment]
Qual é o prazo?
Vamos usar Sass ou CSS puro?

Dependendo das respostas posso fazer o esqueleto.

**Comment by leobaiano** [comment]
O esqueleto seria do HTML + CSS, correto?

**Comment by mksanti** [comment]
O ideal seria fazer com sass, principalmente se vai ter gente colaborando.

**Comment by nicholasio** [comment]
Sim @leobaiano

**Comment by mksanti** [comment]
qual seria o prazo de entrega ?

**Comment by valeriosouza** [comment]
Tem que ficar tudo pronto até dia 15 de Maio, quando será os testes e envio para o repositório oficial.

**Comment by DanielGCarvalho** [comment]
@leobaiano Pensei em um campo customizável. Acredito que é sempre bom ter áreas curinga no layout. Nestes separadores, os administradores vão poder desenvolver toda sua criatividade para a divulgação de algo relevante pra eles. Seja um slide de depos, ou um projeto de grande visibilidade, ou até mesmo uma citação apenas para compor a estrutura.

**Comment by rodrigo-brito** [comment]
Dividir isso vai ser meio foda, mas acho legal passarmos a faca nisso e ir ajeitando aos poucos. Um pega menu, outro os blocos de textos e ícones, outro galeria e outro form e mapa... isso já vai dar o css inicial que pode ser de base para as páginas internas.

**Comment by mksanti** [comment]
paginas internas ? nao ia ser one page ?

**Comment by rodrigo-brito** [comment]
Acho que seria legal pelo menos no caso da galeria do portifólio manter uma página interna, ou faremos um carregamento dinâmico? Deixar tudo na home pode ficar hiper pesado.

**Comment by valeriosouza** [comment]
Estou pensando justamente isso com o @DanielGCarvalho. Eu acho que uma pagina interna fica melhor que modal ou lightbox justamente pra não ficar pesado e ter opções de mais imagens.

**Comment by rodrigo-brito** [comment]
Para categorizar também ajuda bastante, e principalmente para o SEO, manter tudo em uma única página é bem prejudicial

**Comment by leobaiano** [comment]
Eu gosto de ter páginas internas, mas se for para carregar com lightbox é só trazer o conteúdo quando ele for necessário, ao invés de carregar tudo na home, assim não fica pesado.

**Comment by valeriosouza** [comment]
Pode seguir a ideia desse http://themeluxe.com/themes/simpleflex/

**Comment by valeriosouza** [comment]
Faltou ter uma área de blog.

**Comment by DanielGCarvalho** [comment]
Minha ideia inicial foi a seguinte.
Uma galeria de projetos com uma opção de carregar mais projetos, e ao clicar nele, o visitante seria direcionado para uma página de detalhamento.

**Comment by rodrigo-brito** [comment]
O Odin já tem isso estruturado, só estilizar o Header e Footer, o resto fica tranquilo para finalizar a área de blog.

**Comment by DanielGCarvalho** [comment]
Vou implementar também opções de filtragem ( categorias ), e uma área para blog.

**Comment by rodrigo-brito** [comment]
As categorias para o portifólio ia ficar massa no modelo do Isotope, o filtro é bem dinâmico.

**Comment by DanielGCarvalho** [comment]
Ajustes na Home:

• Diminuir o tamanho do barra no menu.
• Incluir botão veja mais na galeria ( Portfólio )
• Incluir novo campo para a área blog.

---

Telas pendentes:

• Blog
• Detalhamento Blog
• Galeria ( Portfólio )
• Detalhamento Galeria ( Portfólio )

---

Vou tentar liberar a home toda configurada, já as demais telas, vou compartilhando na medida do possível!

**Comment by leobaiano** [comment]
@DanielGCarvalho cria issue para isso ai man... outra coisa, o github versiona PSD, então seria bom já colocar ele aqui no repositório.

**Comment by DanielGCarvalho** [comment]
@leobaiano prontinho, issue's criadas! Só vou poder mandar o arquivo hoje no final do dia!

**Comment by leobaiano** [comment]
Mandou bem @DanielGCarvalho

**Comment by brenoalvs** [comment]
Dá pra fazer a estrutura do layout e dividir o restante em components, daí cada um vai pegando um e fazendo! E também acho melhor usarmos Sass.

Só precisaria ter uma estrutura definida das páginas internas, pra fazermos os esqueletos, e depois dividir o restante.

**Comment by valeriosouza** [comment]
Depois criar um arquivo custom.css pra pessoa conseguir personalizar com as mesmas classes

**Comment by nicholasio** [comment]
Melhor orientar a criação de um Child Theme.

Colocaria a observação no próprio style.css. Daí o cara consegue atualizar o tema mais facilmente.

**Comment by rodrigo-brito** [comment]
Show! Vamos começar a passar a faca nessa parada ai, que o churrasco tem que sair até junho! kkkkkkkkkkkk

**Comment by mksanti** [comment]
eu ja crirei uma estrutura inicial... em sass, criei um arquivo com todas as variaveis, outros arquivo como cada componente, e estou utilizando como grid o jeet.gs. Acredito que desta maneira agente nao depende de nenhum framework e fica mais facil para todos contribuirem e modificarem já que esta td modularizado. Estou esperando somente o psd para criar toda a responsividade e mais algumas coisas. depois disso mando um PR para vocês verem se usam esta configuração ou agente planeja outra.

update--
Esqueci mencionar que utilizo grunt e bower para o desenvolvimento caso queiram posso deixar meu arquivos de confg para vocês.

**Comment by rodrigo-brito** [comment]
Mas não ia utilizar o Odin Framework? Ele já possui o Bootstrap integrado.

**Comment by rodrigo-brito** [comment]
Vamos valorizar o peixe da casa... acho bacana mantermos a ideia do Odin.

**Comment by mksanti** [comment]
ok

**Comment by valeriosouza** [comment]
Será usado o Odin

**Comment by nicholasio** [comment]
Usa bootstrap mesmo @mikejavier quando terminar manda pull request para começar a bagaça.

**Comment by mksanti** [comment]
Não sabia... sabia que ia se usar o odin, dei como sugestao agente criar nosso "framework" para nao ter problemas como acontece com o odin atualemente.. ficar dependendo do bootstrap para pequenas coisas.

**Comment by valeriosouza** [comment]
Não vejo problemas em relação ao Odin quanto a isso. Alem do mais isso já foi discutido numa issue que foi fechada

**Comment by rodrigo-brito** [comment]
Acho que não precisa ficar reinventando a roda, o Odin é show! O tema base já é todo responsivo e tem muitas classes que vão ser show de bola para agilizar o desenvolvimento. Odin is life! <3

**Comment by valeriosouza** [comment]
Isso está fora de discussão. Já foi decidido.

**Comment by brenoalvs** [comment]
Podia fazer um PR logo com o Odin, não?
Já dava pra ir dividindo em partials, preparando pra i18n... 

Ou é melhor preparar o front e depois integrar?

-edit-
Botão errado, foi mal. xD

**Comment by valeriosouza** [comment]
Acho que já rola sim @brenoalvs

**Comment by theandersonn** [comment]
O layout do tema já foi definido?
E a parte responsiva?

**Comment by DanielGCarvalho** [comment]
Home publicada, as demais telas eu vou desenvolvendo na medida do possível. A pauta ta lotada ultimamente ahahaha! P.S.: Todas as áreas com interação tem arquivos On e Off ( para a função hover ). Qualquer dúvida é só falar !

**Comment by valeriosouza** [comment]
Deixar claro aqui que esse layout é de uso exclusivo pra esse projeto. Antes que algum espertinho resolva usar ele pra outra coisa. Evite dor de cabeça

**Comment by valeriosouza** [comment]
Continua no #4 e no #16
