### ISSUE TITLE
Bug Contact Form Mobile

### ISSUE THREAD

**Issue by nicholasio** [WordPressBeloHorizonte/horizon-theme#60]
![selecao_018](https://cloud.githubusercontent.com/assets/6104632/7103039/2d93bd9e-e06c-11e4-80c1-edd0b1cc3101.png)

@rodrigo-brito uma dica é você testar com o simulador de smartphone dos próprios navegadores, tanto firefox como chrome tem. Essa imagem é o do Chrome.

**Comment by rodrigo-brito** [comment]
O que está bugando é esse saparador `.horizon-header .sep`
Vou fazer uma media query aqui.
