### ISSUE TITLE
Adicionar mansory na área de portfolio

### ISSUE THREAD

**Issue by brenoalvs** [WordPressBeloHorizonte/horizon-theme#66]
Conversei com o @nicholasio , e achava uma boa adicionar o [Mansory](http://masonry.desandro.com/) na área de portfólio, para fazer os filtros de categorias animados.

Antes que perguntem, prefiro o Mansory ao [Isotope](http://isotope.metafizzy.co/), porque ele já vem embutido no WordPress e acho que ele tem animações mais suaves usando CSS 3, no Isotope não sei como funciona...

Alguém tem algo contra, acha que fica feio, etc?

**Comment by leobaiano** [comment]
@brenoalvs o Mansory e o Isotope não são para criar aqueles mosaicos onde as imagens possuem tamanhos diferentes e tal? O layout prevê as imagens com o mesmo tamanho.

Se estiver falando de usar apenas a animação das imagens na hora do filtro da uma olhada no [Mix It up](https://mixitup.kunkalabs.com/)

**Comment by brenoalvs** [comment]
Legal esse @leobaiano , não conhecia! Ainda tem a função de filtro que queria fazer.
A diferença é que o Mansory já vem no WordPress, o que acha?
E também notei isso no site:  "commercial use requires a commercial license"

O @valeriosouza disse, por exemplo, para não usarmos glyphicons porque tem uma parte paga. Talvez isso o tire da GPL tbm, não?

**Comment by leobaiano** [comment]
Se a licença não permitir então acho melhor usar o mansory mesmo.

**Comment by nicholasio** [comment]
CC (a do mix it up) é incompatível com GPL.

Os temas precisam ser GPL-Compatible. Existem outras licenças derivadas da GPL ou não, mas que são compatíveis com a GPL. Ex: GPL, GPLv2, BSD, MIT.

Acho que o mansory seria uma boa, afinal já vem no WordPress.

**Comment by brenoalvs** [comment]
O Mansory é MIT, por isso tá embutido xD

**Comment by rodrigo-brito** [comment]
Isotope acho que é GPL

**Comment by rodrigo-brito** [comment]
http://isotope.metafizzy.co/license.html

**Comment by valeriosouza** [comment]
Se já vem no WordPress pode ser usado. Assim não precisamos chamar mais nada pra carregar e a licença permite.

**Comment by brenoalvs** [comment]
Galera, desisti do Masonry, pelo menos por enquanto.
Não consegui o efeito que queria, mas depois posso adicioná-lo. Estou deixando por conta do nosso prazo.

Mas estou subindo um PR com alguns ajustes e melhorias nas animações do portfolio.

**Comment by nicholasio** [comment]
Podemos fechar essa issue também?

**Comment by brenoalvs** [comment]
Deixei aberta para fazer um enhacement no futuro, mas vamos fechá-la por enquanto mesmo.
