### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by leobaiano** [WordPressBeloHorizonte/horizon-theme#75]
Ainda não foi definido se será um CPT ou utilizaremos o post padrão do WordPress. Independente de como for feito precisa ter a possibilidade de categorizar os posts.

**Comment by brenoalvs** [comment]
Talvez a gente deva usar os posts padrão mesmo. Como vai pro repositório deve ter alguma regra quanto à isso, não?

**Comment by leobaiano** [comment]
Então vamos fechar com posts padrão, fechou?

**Comment by nicholasio** [comment]
Fechou.
