### ISSUE TITLE
Exibir notificações de dependências

### ISSUE THREAD

**Issue by leobaiano** [WordPressBeloHorizonte/horizon-theme#90]
É preciso exibir uma notificação informando que o tema funciona melhor com a instalação dos plugins listados abaixo:
- Homepage Control
- JetPack

**Comment by valeriosouza** [comment]
@leobaiano ja sabe como fazer isso?

**Comment by valeriosouza** [comment]
Quem não conhece https://github.com/TGMPA/TGM-Plugin-Activation, vamos usar ele

**Comment by tiagorodriguesdev** [comment]
@valeriosousa tem alguém agilizando isso?

**Comment by leobaiano** [comment]
@TiagoRodrigues como ninguém assinou a issue imagino que não tenha ninguém trabalhando nela. Agora veja, antes precisamos definir quais plugins serão obrigatórios ou opcionais, no momento.

@valeriosouza acho que não precisamos de mais uma dependência para fazer isso, é simples de fazer usando o [`admin_notices()`](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices) para exibir as notificações e [`is_plugin_active()`](https://codex.wordpress.org/Function_Reference/is_plugin_active) para verificar se o plugin está ou não ativo.

Vou esperar um pouco, se ninguém tiver uma ideia melhor eu assino a issue e faço logo com os dois plugins que jã sabemos que serão necessários.

**Comment by tiagorodriguesdev** [comment]
@leobaiano se quiser posso agilizar usando admin-notices() e is_plugin_active(), daí vcs conferem e implementam alguma alteração se necessário for

**Comment by leobaiano** [comment]
@TiagoRodrigues por mim tranquilão man, assina a issue e jogue duro. Só da uma pesquisada antes pra ver se essa forma que eu sugeri é realmente a melhor opção, vê o script que o @valeriosouza sugeriu também e depois pode mandar PR que se estiver tudo ok é merge :D

**Comment by tiagorodriguesdev** [comment]
@leobaiano já trabalhei com o TGM em outro projeto uns meses atrás. O Jetpack e Homepage Control vão ser obrigatórios ou recomendados? Se for obrigatório eu prefiro o TGM. Se for recomendado, mas não obrigatório, basta os hooks mesmo
