### ISSUE TITLE
index.php deve mostrar os posts recentes

### ISSUE THREAD

**Issue by nicholasio** [WordPressBeloHorizonte/horizon-theme#92]
Acredito que para ficar de acordo com as regras para o Theme Review team, nós temos que deixar a index.php listando os posts (o index.php deveria ser o blog) e devemos criar um template-homepage.php para mostrar o que hoje temos como homepage.

Ou seja no index.php iria o loop padrão do WordPress com as sidebars (a parte do blog)

E criaríamos um template-homepage.php com o conteúdo abaixo, que hoje está no index.php:

Dessa forma o usuário pode escolher lá em Aparência -> Personalização como será a página inicial dele.

```
    <?php get_template_part('inc/partials/homepage', 'banner'); ?>

    <main id="main-content" class="site-main" role="main">


        <?php if ( function_exists('Homepage_Control') ) : ?>

            <?php do_action('homepage'); ?>

        <?php else: ?>

            <?php get_template_part('inc/partials/homepage'); ?>

        <?php endif; ?>

    </main><!-- #main-content -->
```

**Comment by brenoalvs** [comment]
A index.php precisa ter o loop, porquê é o fallback de todos os arquivos. Mas o quê o Codex diz quando ao uso do front-page.php e home.php?

**Comment by nicholasio** [comment]
@brenoalvs Fiz um PR (#93) que faz o seguinte:
- index.php mostra os posts recentes (página de blog).
- criei um template-homepage.php para ser a página inicial estática (caso o usuário) queira.

Acredito que essa seja a melhor forma, pois é a mais flexível. Pois o usuário pode configurar a página inicial estática para uma página com o template homepage e pode definir uma página para servir de gancho para a listagem de blogs.

**Comment by brenoalvs** [comment]
excelente @nicholasio!

**Comment by valeriosouza** [comment]
Boa @nicholasio
